### ISSUE TITLE
FFmpeg-(RTP/h264)->Janus->janus-rtpforward-plugin-> Will it work?

### ISSUE THREAD

**Issue by robotogre** [michaelfranzl/janus-rtpforward-plugin#11]
Hello,

My use case:

![image](https://user-images.githubusercontent.com/215652/121830717-42502080-cc8b-11eb-9cb9-d6613a1ffcc4.png)

FFmpeg(h264/RTP)->Janus(Streaming Plugin)->janus-rtpforward-plugin->FFmpeg

Will this work? Please note that the original RTP video stream is being created by FFmpeg, and NOT by WebRTC in a web browser.

**Comment by michaelfranzl** [comment]
The only feature of janus-rtpforward-plugin is stated in the README:

> "... takes RTP and RTCP packets from a [Janus session] and forwards/sends them to UDP ports ...".

Based on a cursory glance, it seems that there is no conflict between that and your data flow chart.

As this question seems to be more about application development support, I'll close this issue.
