### ISSUE TITLE
Jitter handling

### ISSUE THREAD

**Issue by B-R-Bender** [michaelfranzl/janus-rtpforward-plugin#13]
Hi @michaelfranzl thanks for this plugin.
I've got a question, do you have an idea of how to handle a jitter on video stream on the receiver side?
What I want to understand If sender got a bad connection, how to handle packet losses.
Thank you in advance.

**Comment by michaelfranzl** [comment]
The plugin is a simple forwarder; it doesn't even know about jitter or lost packets. It seems to me you need to direct that question elsewhere.
